name: Test and upload wheel

on:
  workflow_dispatch:
  push:
    branches:
      - gsk/gh-build-wheel


jobs:
  test-wheel:
    name: Test wheel
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Download package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ubuntu-wheel.yml
          run_id: 1055943805
          name: open3d_linux_x86_64_package
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Test Python package
        run: |
          pip install dist/open3d*.whl pytest
          python -c "import open3d; print('Installed:', open3d)"
          python -c "import open3d; print('CUDA enabled: ', open3d.core.cuda.is_available())"
          pytest python/test --ignore python/test/ml_ops --verbose

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: gsakkis
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
